version: "3.8"

services:
  ml-app:
    build: .
    container_name: fastapi-ml-app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - my_network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:latest
    container_name: redis-db
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
